### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Leon99** [microsoft/DockerTools#204]
While it did work for me a bunch of updates ago, when trying to debug via Docker now, I'm getting this on switching to the Docker profile:
```
========== Checking for Container Prerequisites ==========
Verifying that Docker Desktop is installed...
Docker Desktop is installed.
========== Verifying that Docker Desktop is running... ==========
Verifying that Docker Desktop is running...
Docker Desktop is running.
========== Verifying Docker OS ==========
Verifying that Docker Desktop's operating system mode matches the project's target operating system...
Docker Desktop's operating system mode matches the project's target operating system.
========== Pulling Required Images ==========
Checking for missing Docker images...
Docker images are ready.
========== Warming up container(s) for xxx ==========
Starting up container(s)...
A non-critical error occurred while getting the container(s) ready. Your project(s) will continue to function normally. The error was: Object reference not set to an instance of an object.
```
and then 
`...\.nuget\packages\microsoft.visualstudio.azure.containers.tools.targets\1.7.12\build\Container.targets(196,5): error : Object reference not set to an instance of an object.`
on launching.
Despite the claim that it's a non-critical error, debug doesn't start.

If I remove all the Docker-related stuff and try to re-add it, NuGet ref and Dockerfile are added but not the profile in launchSettings.json, and VS shows this:

**An error occurred while adding Docker File support to this project.**

**Object reference not set to an instance of an object.**

VS 16.2.2, Docker Desktop 2.1.0.1
Any ideas appreciated.

**Comment by Leon99** [comment]
Upgrading microsoft.visualstudio.azure.containers.tools.targets to v1.9.2 didn't help.

**Comment by bwateratmsft** [comment]
@Leon99 Can you share your project?

**Comment by Leon99** [comment]
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <UserSecretsId>22cf960f-xxxx-yyyy-zzzz-21adf2254cdf</UserSecretsId>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <None Include="appsettings.*" Exclude="appsettings.Development.yml" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Swagger\reference-intro.md" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="2.6.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.6.1" />
    <PackageReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.ApplicationInsights.HostingStartup" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Formatters.Json" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.2.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.2.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.9.2" />
    <PackageReference Include="NetEscapades.Configuration.Yaml" Version="1.6.0" />
    <PackageReference Include="NodaTime.Serialization.JsonNet" Version="2.0.0" />
    <PackageReference Include="Polly" Version="7.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="4.0.1" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="4.5.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\xxx\xxx.csproj" />
    <ProjectReference Include="..\yyy\yyy.csproj" />
    <ProjectReference Include="..\zzz\zzz.csproj" />
  </ItemGroup>

</Project>

```
```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "profiles": {
    "Kestrel - Development": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:43001"
    },
    "Kestrel - Test": {
      "commandName": "Project",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Test"
      },
      "applicationUrl": "http://localhost:43001"
    },
    "Docker - Test": {
      "commandName": "Docker",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Test"
      }
    }
  }
}
```

**Comment by bwateratmsft** [comment]
Thanks @Leon99. The launchSettings.json file is missing the iisSettings section which is normally present. In VS 2019 16.3 Preview 2, we fixed an issue with gRPC projects due to the same bug, so it is already fixed in future releases.

In the meantime, I think as a workaround, you can add that section to the top of the launchSettings.json--it doesn't really matter what the values are:

```
{
  "$schema": "http://json.schemastore.org/launchsettings.json",
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:43001"
    }
  },
  "profiles": {
    "Kestrel - Development": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:43001"
    },
    "Kestrel - Test": {
      "commandName": "Project",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Test"
      },
      "applicationUrl": "http://localhost:43001"
    },
    "Docker - Test": {
      "commandName": "Docker",
      "launchBrowser": false,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Test"
      }
    }
  }
}

**Comment by AndyPook** [comment]
ummm, why do we need `iisSetting` when it's running in a container with kestrel?

**Comment by bwateratmsft** [comment]
@AndyPook We use the `iisSettings` as a hint to what the Kestrel settings should be in the container. Due to a bug it fails if the `iisSettings` aren't present. This bug is fixed in 16.3.

**Comment by Robar666** [comment]
Hi,

I'm working on VS 2019 16.3.8 (`Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.9.5`) and have a Kestrel setup. 
I'm still getting the `Object reference not set to an instance of an object` error if I want to launch my Docker profile and no `iisSettings` section is present.

So I still have to use the workaround and add an empty `iisSetting` section add the top of the `launchSettings.json` to work with Docker. So I guess this issue still persists or do I need to update something else?

**Comment by bwateratmsft** [comment]
@pratiksanglikar Do you know if this bug came back in 16.3.8?

**Comment by pratiksanglikar** [comment]
@bwateratmsft Yes, it appears that it regressed in 16.3.8.
@NCarlsonMSFT just finished the PR to fix this and it would be available in 16.5.
